name: crowdcuts
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.10
  universal_html: ^2.0.8
  cached_network_image: ^3.3.1
  http: ^1.2.1
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: any
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/crowdcutsbg.png
    - assets/crowdcutslogo.png
    - assets/crowdcutslogo2.png
    - assets/male.jpg
    - assets/female.jpg
    - assets/short.png
    - assets/medium.png
    - assets/long.png
    - assets/oval.png
    - assets/round.png
    - assets/square.png
    - assets/heart.png
    - assets/diamond.png
    - assets/straight.png
    - assets/wavy.png
    - assets/curly.png
    - assets/thin.png
    - assets/mediumDensity.png
    - assets/thick.png
  uses-material-design: true
